export const LOGIN_ROUTE = '/login'
export const NOT_FOUND_ROUTE = '/error'
export const REQUESTS_ROUTE = '/requests'
export const USERS_ROUTE = '/users'
export const CREATE_USER_ROUTE = USERS_ROUTE + '/create'
